# Generated by Django 4.1.9 on 2023-05-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_remove_user_last_login_remove_user_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
